### ISSUE TITLE
Problem starting the web container

### ISSUE THREAD

**Issue by bravera** [anokun7/microservices-demo#4]
Hi 
I am having a problem getting this to work with my Swarm set up.
This is the error I see...

Creating microservicesdemo_dbdata_1
Creating microservicesdemo_db_1
Creating microservicesdemo_lb_1
Creating microservicesdemo_web_1
ERROR: unable to find a node that satisfies image==microservicesdemo_web

Seems to be looking for some node affinity based on availability of the web image, but I cant see where that is specified or why.
My swarm cluster has 1 master and 1 slave, and the dbdata, db and lb containers all seem to be created quite happily.

Any ideas?

**Comment by anokun7** [comment]
The node where you are running this, is that part of the swarm cluster? What do you see when you run `docker info` after you see the error message?
